name: epsi_sorcier_qcm
description: QCM local - Quel sorcier de l'EPSI es-tu?
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  lottie: ^2.3.0
  google_fonts: ^4.0.3
  share_plus: ^10.0.0  # Changed from ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/quiz.json
    - assets/lottie/patronus.json
